[package]
name = "nf-rated"
version = "0.1.0"
authors = ["Thorsten Lorenz <thlorenz@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.0"
csv = "1.1.3"

[[bin]]
name="update_data"
path= "src/update_data.rs"
