[package]
name = "nf-rated"
version = "0.1.0"
authors = ["Thorsten Lorenz <thlorenz@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.0"
csv = "1.1.3"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
serde = { version = "1.0.116", features = ["derive"] }

[[bin]]
name="sync_ratings"
path= "src/sync_ratings.rs"

[[bin]]
name="init_data"
path= "src/init_data.rs"
